In [7]:
import pandas
a=[1,7,2]
myvar=pandas.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64

In [6]:
import pandas as pd 
print(pd.__version__)

3.0.3

In [10]:
import pandas as pd 
a = [1, 7, 2] 
myvar = pd.Series(a, index = ["x", "y", "z"]) 
print(myvar) 
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7

In [ ]:
# D A T A F R A M E S :-
df = pd.DataFrame({"calories": [420, 380, 390], "duration": [50, 40, 45]})
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [128]:
import pandas as pd
df1 = pd.DataFrame({'Id':[1,2,3,4], 'Name':['A1','A2','A3','A4'], 'Subject':['sub1','sub2','sub3','sub4']})
df2 = pd.DataFrame({'Id':[2,1,3,4], 'Name':['B1','B2','B3','B4'], 'Subject':['sub5','sub1','sub4','sub6']})                    
print(df1);                        print("\n")
print(df2);                        print("\n")
print(pd.concat([df1, df2]));      print("\n")
print("\n Addition\n", df1+df2);   print("\n")

   Id Name Subject
0   1   A1    sub1
1   2   A2    sub2
2   3   A3    sub3
3   4   A4    sub4


   Id Name Subject
0   2   B1    sub5
1   1   B2    sub1
2   3   B3    sub4
3   4   B4    sub6


   Id Name Subject
0   1   A1    sub1
1   2   A2    sub2
2   3   A3    sub3
3   4   A4    sub4
0   2   B1    sub5
1   1   B2    sub1
2   3   B3    sub4
3   4   B4    sub6



 Addition
    Id  Name   Subject
0   3  A1B1  sub1sub5
1   3  A2B2  sub2sub1
2   6  A3B3  sub3sub4
3   8  A4B4  sub4sub6

In [129]:
# R O W - W I S E - C O N C A T E N A T I O N :
pd.concat([df1, df2], axis=1)
#pd.concat([df1, df2], axis=0)

   Id Name Subject  Id Name Subject
0   1   A1    sub1   2   B1    sub5
1   2   A2    sub2   1   B2    sub1
2   3   A3    sub3   3   B3    sub4
3   4   A4    sub4   4   B4    sub6

In [130]:
# Syntax for joining on a specific column
pd.merge(df1, df2, on='Id', how='left')

   Id Name_x Subject_x Name_y Subject_y
0   1     A1      sub1     B2      sub1
1   2     A2      sub2     B1      sub5
2   3     A3      sub3     B3      sub4
3   4     A4      sub4     B4      sub6

In [131]:
print(pd.merge(df1, df2, left_on='Name', right_on='Subject', how='outer'))

   Id_x Name_x Subject_x  Id_y Name_y Subject_y
0   1.0     A1      sub1   NaN    NaN       NaN
1   2.0     A2      sub2   NaN    NaN       NaN
2   3.0     A3      sub3   NaN    NaN       NaN
3   4.0     A4      sub4   NaN    NaN       NaN
4   NaN    NaN       NaN   1.0     B2      sub1
5   NaN    NaN       NaN   3.0     B3      sub4
6   NaN    NaN       NaN   2.0     B1      sub5
7   NaN    NaN       NaN   4.0     B4      sub6

In [132]:
print(df1.join(df2, lsuffix='_left', rsuffix='_right'))

   Id_left Name_left Subject_left  Id_right Name_right Subject_right
0        1        A1         sub1         2         B1          sub5
1        2        A2         sub2         1         B2          sub1
2        3        A3         sub3         3         B3          sub4
3        4        A4         sub4         4         B4          sub6

In [133]:
res = pd.concat([df1,df2], keys=['x', 'y'])
print(res)
res.loc['x']

     Id Name Subject
x 0   1   A1    sub1
  1   2   A2    sub2
  2   3   A3    sub3
  3   4   A4    sub4
y 0   2   B1    sub5
  1   1   B2    sub1
  2   3   B3    sub4
  3   4   B4    sub6

   Id Name Subject
0   1   A1    sub1
1   2   A2    sub2
2   3   A3    sub3
3   4   A4    sub4

In [134]:
ws = df1[df1["Name"] != 0]
print(ws)

   Id Name Subject
0   1   A1    sub1
1   2   A2    sub2
2   3   A3    sub3
3   4   A4    sub4

In [135]:
import pandas as pd
# Inner join: keeps only rows where 'A' matches in both (1 and 2)
rs = pd.merge(df1, df2, on='Subject', suffixes=('_df1', '_df2'))
print(rs)

   Id_df1 Name_df1 Subject  Id_df2 Name_df2
0       1       A1    sub1       1       B2
1       4       A4    sub4       3       B3

In [136]:
# Left Join: Keeps all rows from df1
pd.merge(df1, df2, on='Subject', how='left')

   Id_x Name_x Subject  Id_y Name_y
0     1     A1    sub1   1.0     B2
1     2     A2    sub2   NaN    NaN
2     3     A3    sub3   NaN    NaN
3     4     A4    sub4   3.0     B3

In [137]:
# Right Join: Keeps all rows from df2
pd.merge(df1, df2, on='Subject', how='right')

   Id_x Name_x Subject  Id_y Name_y
0   NaN    NaN    sub5     2     B1
1   1.0     A1    sub1     1     B2
2   4.0     A4    sub4     3     B3
3   NaN    NaN    sub6     4     B4

In [138]:
# Outer Join: Keeps all rows from both (fills blanks with NaN)
pd.merge(df1, df2, on='Subject', how='outer')

   Id_x Name_x Subject  Id_y Name_y
0   1.0     A1    sub1   1.0     B2
1   2.0     A2    sub2   NaN    NaN
2   3.0     A3    sub3   NaN    NaN
3   4.0     A4    sub4   3.0     B3
4   NaN    NaN    sub5   2.0     B1
5   NaN    NaN    sub6   4.0     B4

In [139]:
res = pd.merge(df1, df2, left_index=True, right_index=True, suffixes=('_1', '_2'))
print(res)

res = pd.concat([df1, df2], ignore_index=True)
print(res)

   Id_1 Name_1 Subject_1  Id_2 Name_2 Subject_2
0     1     A1      sub1     2     B1      sub5
1     2     A2      sub2     1     B2      sub1
2     3     A3      sub3     3     B3      sub4
3     4     A4      sub4     4     B4      sub6
   Id Name Subject
0   1   A1    sub1
1   2   A2    sub2
2   3   A3    sub3
3   4   A4    sub4
4   2   B1    sub5
5   1   B2    sub1
6   3   B3    sub4
7   4   B4    sub6

In [143]:
res = df1.merge(df2,on='Subject',how='left')
print(res)

   Id_x Name_x Subject  Id_y Name_y
0     1     A1    sub1   1.0     B2
1     2     A2    sub2   NaN    NaN
2     3     A3    sub3   NaN    NaN
3     4     A4    sub4   3.0     B3

In [147]:
res = df1.merge(df2,on='Subject',how='right')
print(res)

   Id_x Name_x Subject  Id_y Name_y
0   NaN    NaN    sub5     2     B1
1   1.0     A1    sub1     1     B2
2   4.0     A4    sub4     3     B3
3   NaN    NaN    sub6     4     B4

In [144]:
res = df1.merge(df2,on='Subject',how='outer')
print(res)

   Id_x Name_x Subject  Id_y Name_y
0   1.0     A1    sub1   1.0     B2
1   2.0     A2    sub2   NaN    NaN
2   3.0     A3    sub3   NaN    NaN
3   4.0     A4    sub4   3.0     B3
4   NaN    NaN    sub5   2.0     B1
5   NaN    NaN    sub6   4.0     B4

In [145]:
res = df1.merge(df2,on='Subject',how='inner')
print(res)

   Id_x Name_x Subject  Id_y Name_y
0     1     A1    sub1     1     B2
1     4     A4    sub4     3     B3